<?php

namespace Pagilla\Core\Component\Html;

class EventAttributes
{
    public function __construct(
        string $onAfterPrint = null,
        string $onBeforePrint = null,
        string $onBeforeUnload = null,
        string $onError = null,
        string $onHashChange = null,
        string $onLoad = null,
        string $onMessage = null,
        string $onOffline = null,
        string $onOnline = null,
        string $onPageHide = null,
        string $onPageShow = null,
        string $onPopState = null,
        string $onResize = null,
        string $onStorage = null,
        string $onUnload = null,
        string $onBlur = null,
        string $onChange = null,
        string $onContextMenu = null,
        string $onFocus = null,
        string $onInput = null,
        string $onInvalid = null,
        string $onReset = null,
        string $onSearch = null,
        string $onSelect = null,
        string $onSubmit = null,
        string $onKeyDown = null,
        string $onKeyPress = null,
        string $onKeyUp = null,
        string $onClick = null,
        string $onDblClick = null,
        string $onMouseDown = null,
        string $onMouseMove = null,
        string $onMouseOut = null,
        string $onMouseOver = null,
        string $onMouseUp = null,
        string $onMouseWheel = null,
        string $onWheel = null,
        string $onDrag = null,
        string $onDragEnd = null,
        string $onDragEnter = null,
        string $onDragLeave = null,
        string $onDragOver = null,
        string $onDragStart = null,
        string $onDrop = null,
        string $onScroll = null,
        string $onCopy = null,
        string $onCut = null,
        string $onPaste = null,
        string $onAbort = null,
        string $onCanPlay = null,
        string $onCanPlayThrough = null,
        string $onCueChange = null,
        string $onDurationchange = null,
        string $onEmptied = null,
        string $onEnded = null,
        string $onLoadedData = null,
        string $onLoadedMetadata = null,
        string $onLoadStart = null,
        string $onPause = null,
        string $onPlay = null,
        string $onPlaying = null,
        string $onProgress = null,
        string $onRateChange = null,
        string $onSeeked = null,
        string $onSeeking = null,
        string $onStalled = null,
        string $onSuspend = null,
        string $onTimeUpdate = null,
        string $onVolumeChange = null,
        string $onWaiting = null,
        string $onToggle = null,
    ) {
    }


}
